eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: rol
          uri: http://localhost:3000
          predicates:
            - Path=/api/rol**

        - id: ministerial
          uri: http://localhost:3000
          predicates:
            - Path=/api/ministerial**

        - id: teamPesca
          uri: http://localhost:3000
          predicates:
            - Path=/api/team_pesca**
        - id: church
          uri: http://localhost:3000
          predicates:
            - Path=/api/church**

        - id: user
          uri: http://localhost:3000
          predicates:
            - Path=/api/user**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG